openai:
  api_key: ${OPENAI_API_KEY}
  model: gpt-4

agent:
  name: GrowAI
  initial_prompt: "You are GrowAI, an AI that recursively improves and extends its codebase. Start by analyzing your codebase and proposing enhancements."
  max_iterations: 100

version_control:
  # Name of the Git remote to push to (e.g., 'origin')
  remote_name: origin
  # SSH or HTTPS URL of your GitHub repository
  remote_url: git@github.com:vjvasiljev/SelfGrowAI.git
  # Branch to push changes to
  branch: main
